variable "create_this" {
  description = "Controls if this resource should be created (it affects almost all resources)"
  type        = bool
  default     = true
}

variable "action" {
  description = "The AWS Lambda action you want to allow in this statement."
  type        = string
}

variable "event_source_token" {
  description = "(Optional) The Event Source Token to validate."
  type        = string
  default     = null
}

variable "function_name" {
  description = "Name of the Lambda function whose resource policy you are updating"
  type        = string
}

variable "function_url_auth_type" {
  description = "(Optional) Lambda Function URLs authentication type. Valid values are: AWS_IAM or NONE."
  type        = string
  default     = null
}

variable "principal" {
  description = "The principal who is getting this permission e.g., s3.amazonaws.com, an AWS account ID, or AWS IAM principal, or AWS service principal such as events.amazonaws.com or sns.amazonaws.com."
  type        = string
}

variable "qualifier" {
  description = "(Optional) Query parameter to specify function version or alias name. The permission will then apply to the specific qualified ARN."
  type        = string
  default     = null
}

variable "source_account" {
  description = "(Optional) This parameter is used when allowing cross-account access, or for S3 and SES."
  type        = string
  default     = null
}

variable "source_arn" {
  description = "(Optional) When the principal is an AWS service, the ARN of the specific resource within that service to grant permission to."
  type        = string
  default     = null
}

variable "statement_id" {
  description = "(Optional) A unique statement identifier. By default generated by Terraform."
  type        = string
  default     = null
}

variable "statement_id_prefix" {
  description = "(Optional) A statement identifier prefix. Terraform will generate a unique suffix."
  type        = string
  default     = null
}

variable "principal_org_id" {
  description = "(Optional) The identifier for your organization in AWS Organizations."
  type        = string
  default     = null
}
