---
name: GitHub Actions Push
on:
  push:
    branches-ignore:
      - main
      - next

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-west-2
        SOURCE_REPO_URL: $GITHUB_REPOSITORY
        SOURCE_REPO_BRANCH: $GITHUB_REF_NAME
      options: --cpus 1
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Check AWS credentials
        uses: docker://amazon/aws-cli
        with:
            args: sts get-caller-identity
      - name: Run terraform check on environment/events
        run: |
          cd test/environment/events
          terraform init
          terraform plan
